### ISSUE TITLE
Mac上的Android Studio，打开lotties的json文件直接卡死

### ISSUE THREAD

**Issue by dwzrlp** [YangLang116/MediaFilePreviewer#4]
你好，Mac上的Android Studio，打开lottie的json文件直接卡死
Android Studio版本2022.1.1 Patch 2
以前可以打开，很久没开过了，今天突然开就直接卡死Android Studio，要强制退出才行

**Comment by YangLang116** [comment]
方便提供对应的lottie文件吗?

**Comment by dwzrlp** [comment]
> 方便提供对应的lottie文件吗?

你好，是所有的lottie，在Windows上试了一下都没问题，但在macOS上就卡死了

**Comment by YangLang116** [comment]
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.2
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8

升级到

Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.2
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8

没发现卡顿问题，可以在仓库的 [plugin-version](https://github.com/YangLang116/MediaFilePreviewer/tree/main/plugin-version) 下载可用的版本

**Comment by dwzrlp** [comment]
> Android Studio Dolphin | 2021.3.1 Patch 1 Build #AI-213.7172.25.2113.9123335, built on September 30, 2022 Runtime version: 11.0.13+0-b1751.21-8125866 x86_64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. macOS 11.2.2 GC: G1 Young Generation, G1 Old Generation Memory: 1280M Cores: 8
> 
> 升级到
> 
> Android Studio Electric Eel | 2022.1.1 Patch 2 Build #AI-221.6008.13.2211.9619390, built on February 17, 2023 Runtime version: 11.0.15+0-b2043.56-8887301 x86_64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. macOS 11.2.2 GC: G1 Young Generation, G1 Old Generation Memory: 1280M Cores: 8
> 
> 没发现卡顿问题，可以在仓库的 [plugin-version](https://github.com/YangLang116/MediaFilePreviewer/tree/main/plugin-version) 下载可用的版本

你好，感谢回复。我尝试了卸载掉[MediaFilePreviewer](https://github.com/YangLang116/MediaFilePreviewer)，即可正常打开lottie的json文件，直接显示的json内容，我尝试了在仓库的 [plugin-version](https://github.com/YangLang116/MediaFilePreviewer/tree/main/plugin-version) 下载1.0.9，还是一样直接卡死；又试了1.0.8，还是直接卡死。

**Comment by dwzrlp** [comment]
使用[MediaFilePreviewer](https://github.com/YangLang116/MediaFilePreviewer)打开svg和webp都没问题，就是lottie直接卡死

**Comment by YangLang116** [comment]
我这边多次验证没发现这个问题，如果可以的话，能重新安装IDEA，或者提供一下日志文件(Help -> Show Log in Finder 里面的 idea.log文件）

**Comment by dwzrlp** [comment]
> 我这边多次试验没有发现这个问题，如果可以的话，可以重新安装IDEA，或者提供下一次日志文件（帮助->在Finder里显示登录idea.log文件）

你好，我试了用PyCharm和WebStorm，没有问题，可以打开。仅仅Android Studio有问题，我试试重装

**Comment by dwzrlp** [comment]
我换了全新的Mac安装全新的Android Studio，依然报错卡死，
java.lang.NoSuchMethodError: 'void com.intellij.ide.IdeEventQueue.unsafeNonblockingExecute(java.lang.Runnable)'
	at com.intellij.ui.javafx.JavaFxHtmlPanel.runFX(JavaFxHtmlPanel.java:115)
	at com.intellij.ui.javafx.JavaFxHtmlPanel.lambda$new$6(JavaFxHtmlPanel.java:52)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by YangLang116** [comment]
可以尝试打开jcef功能，jcef是intellij官方推荐的，AndroidStudio一直是关闭的，https://www.jianshu.com/p/68056562d1c4

**Comment by dwzrlp** [comment]
> 可以尝试打开jcef功能，jcef是intellij官方推荐的，AndroidStudio一直是关闭的，https://www.jianshu.com/p/68056562d1c4

感谢，问题解决
